name: Check that the code runs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_run:
    name: Check that tutorials run

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]
        day: [1, 2, 3]

    steps:
    - run: |
        echo "Testing Day ${day} Tutorials on ${python-version}"
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v3
    - name: Installing requirements
      run: |
        conda env create -f environment.yml
    - name: Test notebooks execution
      run: |
        conda activate igwn-py39-lw
        for file in Tutorials/Day_"${day}"/*ipynb; do
            echo "Checking ${file}";
            if ! ./tests/check_run.sh "${file}"; then
                echo "::error file=${file},title=Error";
                exit 1;
            fi
        done
